##
## Configuration for the dvswitch-dashboard
##
Alias /dvswitch /usr/share/dvswitch

#       SetEnvIf Request_URI "^/dvswitch/include/status\.php$" dontlog=1
#	SetEnvIf Request_Method ^GET$ dontlog

#	CustomLog ${APACHE_LOG_DIR}/access.log combined env=!dontlog


<Directory /usr/share/dvswitch>
	AllowOverride all

    # Implement rewrite within the directory so that is survives
    # into the <VirtualHost> tags
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule ^ws/([0-9]+) ws://localhost:$1 [P,L,QSA]
</Directory>

# Proxy can't usefully occur inside a <Directory> on Debian
#ProxyAddHeaders On
#ProxyPreserveHost On
#ProxyPass /allmon3/master/ "http://localhost:16080/"

