
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_stream-response-bodyDetails

# config options to stream response allows admin to configure if response is collected in entirety prior to sending data to client

# server.stream-response-body = 0	default: buffer entire response body before sending to client
# server.stream-response-body = 1	stream response body to client; buffer to temp files
# server.stream-response-body = 2	stream response body to client; minimal buffering might block backend

server.stream-response-body = 2
